### ISSUE TITLE
ubuntu 16.04 make出的问题

### ISSUE THREAD

**Issue by borispub** [six-ddc/httpflow#1]
g++ -O2 -c http_flow.cpp -o http_flow.o
http_flow.cpp: In function ‘std::__cxx11::string timeval2tr(const timeval*)’:
http_flow.cpp:214:116: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘__suseconds_t {aka long int}’ [-Wformat=]
     sprintf(&time_str[0], "%02d:%02d:%02d.%06d", local_tm->tm_hour, local_tm->tm_min, local_tm->tm_sec, ts->tv_usec);
                                                                                                                    ^

**Comment by six-ddc** [comment]
这只是警告，编译成功了吧

**Comment by borispub** [comment]
boris@boris-ThinkPad-X1-Carbon-4th:~/httpflow$ make
g++ -O2 -c http_flow.cpp -o http_flow.o
http_flow.cpp: In function ‘std::__cxx11::string timeval2tr(const timeval*)’:
http_flow.cpp:214:116: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘__suseconds_t {aka long int}’ [-Wformat=]
 02d.%06d", local_tm->tm_hour, local_tm->tm_min, local_tm->tm_sec, ts->tv_usec);
                                                                              ^
g++ -O2 -c http_parser.cpp -o http_parser.o
g++ -lz -lpcap http_flow.o http_parser.o -o httpflow
http_flow.o: In function `gzip_decompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) [clone .constprop.77]':
http_flow.cpp:(.text+0x296): undefined reference to `inflateInit2_'
http_flow.cpp:(.text+0x2e8): undefined reference to `inflate'
http_flow.cpp:(.text+0x31f): undefined reference to `inflateEnd'
http_flow.o: In function `print_usage()':
http_flow.cpp:(.text+0xe19): undefined reference to `pcap_version'
http_flow.cpp:(.text+0xe23): undefined reference to `pcap_version'
http_flow.o: In function `init_capture_config(int, char**, capture_config*, char*)':
http_flow.cpp:(.text+0x146c): undefined reference to `pcap_lookupdev'
http_flow.o: In function `main':
http_flow.cpp:(.text.startup+0x75): undefined reference to `pcap_lookupnet'
http_flow.cpp:(.text.startup+0x95): undefined reference to `pcap_open_live'
http_flow.cpp:(.text.startup+0xc6): undefined reference to `pcap_compile'
http_flow.cpp:(.text.startup+0xdc): undefined reference to `pcap_setfilter'
http_flow.cpp:(.text.startup+0xef): undefined reference to `pcap_freecode'
http_flow.cpp:(.text.startup+0x102): undefined reference to `pcap_loop'
http_flow.cpp:(.text.startup+0x151): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x184): undefined reference to `pcap_open_offline'
http_flow.cpp:(.text.startup+0x1cd): undefined reference to `pcap_fopen_offline'
http_flow.cpp:(.text.startup+0x1f7): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x22b): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x23d): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x29b): undefined reference to `pcap_geterr'
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by borispub** [comment]
出现“collect2: ld returned 1 exit status”的错误是因为申明了函数却没实现，一般是链接阶段出现

**Comment by six-ddc** [comment]
* On CentOS
yum install libpcap-devel zlib-devel

* On Ubuntu
apt-get install libpcap-dev zlib1g-dev

make之前需要安装对应的依赖包
